# Generated by Django 3.0.5 on 2020-04-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
