# Generated by Django 3.0.5 on 2020-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20200415_1429'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knockoutmatchprediction',
            constraint=models.UniqueConstraint(fields=('tournament', 'friend', 'match_number'), name='unique_ko_match_prediction'),
        ),
        migrations.AddConstraint(
            model_name='topscorer',
            constraint=models.UniqueConstraint(fields=('tournament', 'friend'), name='unique_top_scorer'),
        ),
    ]
