# Generated by Django 3.2 on 2021-05-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_matchinfo_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='away_team_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='home_team_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
