# Generated by Django 3.2 on 2021-05-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20210508_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscore',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='home_team_name',
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='away_team_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='home_team_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
