# Generated by Django 3.2 on 2021-05-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_auto_20210508_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='home_win',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
